server:
  # 端口
  port: 8080
# 数据库连接
spring:
  profiles:
    active: @profileActive@
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    locale: zh_CN
    # 解决json返回过程中long的精度丢失问题
    generator:
      write-numbers-as-strings: true
      write-bigdecimal-as-plain: true
    serialization:
      write-dates-as-timestamps: false
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    servlet:
      load-on-startup: 1 #SpringBoot的接口第一次访问都很慢，通过日志可以发现，dispatcherServlet不是一开始就加载的，有访问才开始加载的，即懒加载。
  # 防止bean重复覆盖的策略
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  global-config:
    banner: false

knife4j:
  enable: true
  openapi:
    title: SimonBaseDoc
    description: "接口测试文档"
    email: xusenhao1123@163.com
    concat: Tomato
    url: https://docs.senhao.top
    version: v1.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: simon
        api-rule: package
        api-rule-resources:
          - com.simon